baseURL = "http://example.org/"
languageCode = "en-us"
title = "Guru Gobind Seva Sansthan"
 

# The sites parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 1
      name = "HOME"
      url = "/"
    [[menu.header]]
      weight = 2
      name = "GALLERY"
      url = "#gallery"  
    [[menu.header]]
      weight = 3
      name = "CONTACT"
      url = "#contact"

	[params.hero]
		title="GURU GOBIND SEWA SANSTHAN"
		subtitle=""
		button="DONATE"
		url="#contact"

	[params.about]
		title="About"
		img = "../images/da.jpg"
		description="Our trust Shri Guru Gobind Singh Ji Sarv Dharam Parkashta Sewa Sanshtan was founded in 2015 with the inspiration of Shri Arjinder Singh living in Canada. Guru Gobind Sewa Sansthan aims to educate poverty affected children living in slum areas so they can become useful members of society. Our Trust's main focus is to serve all regardless of religion or caste through education and health."
 

	[params.team]
		title="Our Team"

		[[params.team.members]] 
		  name = "Shri Arjinder Singh"
		  img = "../images/arjinder-singh.jpg"
		  text="Mr Arjinder Singh ji is from  Bijnor, Uttar Pradesh India and now lives in Canada. Mr Singh has the intent and provided the motivation to establish Guru Gobind Singh Ji Sarv Dharam Parkastha Sewa Sanshtan in order to serve slum areas of Uttar Pradesh State and remote interior villages of Uttarakhand through Medical and Educational Sewa (Selfless Service) welcoming and including people of all castes and religions equally."
    	[[params.team.members]] 
		  name = "Dr. Atul Negi"
		  img = "../images/da.jpg"
		  text= "Dr Atul Singh Negi has been working in a Government Ayurvedic Hospital in  Gaindkhal, Pauri Garhwal, India since 2013 providing health treatment to rural villagers. Dr Atul also provides free education to disadvantaged students and also promotes forest conservation, plantations and spreads awareness about the importance of caring for the environment."
    	     	
	
	[params.banking]
		  title="Banking Details"
		  accountname="Shri Guru Gobind Singh Ji Sarv Dharam Parkastha Sewa Sanshtan"
          accountnumber="0357000103612226"
          ifsc="PUNB0035700"
          bank="Punjab National Bank"
		  branch=" Najibabad, Bijnor, Uttar Pradesh"
	
	[params.form]
		  title="Write to us."
		  button="SUBMIT"	  